version: 2.1
jobs:
  install:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.12.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./node_modules
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.12.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: test
          command: yarn test
      - store_artifacts:
          path: coverage
          prefix: coverage
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.12.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: build
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./.next
  deploy:
    docker:
      - image: circleci/node:11.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: install now
          command: yarn global add now
      - run:
          name: deploy
          command: yarn deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
          filters:
            branches:
              ignore: master
      - build:
          requires:
            - install
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

